basePath: /
host: localhost:8888
info:
  contact:
    email: soberkoder@gmail.com
    name: API Support
  description: This is a sample service for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: "1.0"
paths:
  /delete:
    delete:
      consumes:
      - application/json
      description: Delete persons by id from users
      parameters:
      - description: delete user
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: '{code:400, msg:"failure"}'
          schema:
            type: string
      summary: Delete persons by id from users
      tags:
      - users
  /insert:
    post:
      consumes:
      - application/json
      description: Insert persons into users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
      summary: Insert persons into users
      tags:
      - users
  /show:
    get:
      consumes:
      - application/json
      description: Show persons in users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
      summary: Show persons in users
      tags:
      - users
  /update:
    put:
      consumes:
      - application/json
      description: Update persons in users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
      summary: Update persons in users
      tags:
      - users
swagger: "2.0"
